---
title: "Analyse of TradePerformance"
author: "Andrei Pazniak"
date: "February 3, 2016"
output: html_document
---

```{r, echo=FALSE, warning=F}
require(data.table)
require(ggplot2)

file <- paste(tempdir(), "_ptempdownload.zip", sep =  "")
download.file("https://raw.githubusercontent.com/SoftFx/FdkUtilities/master/CSharp/TradePerformance/Results/Development/20160216-171701_Development_FIXLogsOn_TTSLogsOn_MonitoringOn_QuotesOn.txt", file, mode="wb") 
#d<-read.csv(unzip(file), header=T)
d<-read.csv(file, header=T)
d<-as.data.table(d)
d<-d[TestNumber==1,]

```

Number of executed orders by account and ReqPerSec
```{r}
table(d$Account, d$OPS_Req, d$TestNumber)

      print("Top longest execution")    
      print(d[order(-Total)][1:10,])
      
      print("Worst New execution")    
      print(d[order(-New)][1:10,])
      
      print("Worst Calculated1 execution")    
      print(d[order(-Calculated1)][1:10,])
      
      print("Worst Filled execution")    
      print(d[order(-Filled)][1:10,])
      
      print("Proprtion delay for each execution staqge")
      print ( apply( apply(d[,7:10, with=F], 1, prop.table), 1, mean) )
```

Summary execution time ~ requested orders per second
```{r}
d[,OPS_Req:=OPS_Req * TestNumber]
d[,OPS_Mean:=OPS_Mean * TestNumber]

si<-rbind( tapply(d$Total, d$OPS_Req, length), 
           tapply(d$Total, d$OPS_Req, min),
           tapply(d$Total, d$OPS_Req, mean), 
           tapply(d$Total, d$OPS_Req, median), 
           tapply(d$Total, d$OPS_Req, max), 
           tapply(d$Total, d$OPS_Req, sd))
rownames(si)<-c("length", "min", "mean", "median", "max", "sd")
si<-round(t(si))
ggplot(melt(si), aes(Var1, value)) + geom_point() + facet_grid(Var2 ~ ., scales = "free") + xlab("Requested Orders Per Second")
```


Scaling
```{r}
ggplot( d, aes(x=OPS_Req, y=OPS_Mean)) + geom_line() + geom_abline(intercept = 0, slope = 1,  size=2, color='red')
```